drop table if exists users;

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email    VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(20)  NOT NULL,
    status   VARCHAR(20)  NOT NULL,
    id_main  BIGINT       NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uq_users_email UNIQUE (email)
);

insert into users(email, password, role, status, id_main)
values ('admin@admin.ru', '$2y$12$rm81Q25xrn1KmDHz2dsAq.lE5yLGXQxi/Zly/TBytl4S.Ge.zSup.', 'ADMIN', 'ACTIVE', 1);