version: '3.1'
services:
  security-db:
    image: redis:7.2.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=root

  security-service:
    build:
      context: ssai-security/ssai-security-server
      dockerfile: Dockerfile
    image: security_image
    container_name: security_container
    ports:
      - "7070:7070"
    depends_on:
      - security-db
      - main-server
      - stats-server
    environment:
      - API_REDIS_HOST=redis
      - STATS_SERVER_URL=http://stats-server:9090
      - MAIN_SERVER_URL=http://main-server:8080

  stats-db:
    image: postgres:14-alpine
    container_name: db_stats_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=softplat-stats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

  stats-server:
    build: /ssai-stats/ssai-stats-server
    image: stats_server_image
    container_name: stats_server_container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/softplat-stats
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=password

  main-db:
    image: postgres:14-alpine
    container_name: db_main_container
    ports:
      - "6545:5432"
    environment:
      - POSTGRES_DB=softmain
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  main-server:
    build: /ssai-main/ssai-main-server
    image: main_image
    container_name: main_container
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/softmain
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats-server:9090