drop table if exists stat_buyer, stat_seller, stat_product, statistic cascade;

CREATE TABLE IF NOT EXISTS stat_buyer
(
    id                BIGINT NOT NULL,
    name              VARCHAR(20) NOT NULL,
    CONSTRAINT pk_stat_buyer PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stat_seller
(
    id                BIGINT NOT NULL,
    name              VARCHAR(20)                 NOT NULL,
    CONSTRAINT pk_stat_seller PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stat_product
(
    id                 BIGINT NOT NULL,
    name               VARCHAR(255)            NOT NULL,
    seller_id          BIGINT                  NOT NULL,
    CONSTRAINT pk_stat_product PRIMARY KEY (id),
    CONSTRAINT fk_stat_seller FOREIGN KEY (seller_id) REFERENCES stat_seller (id)
);

CREATE TABLE IF NOT EXISTS statistic
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    buyer_id   BIGINT ,
    product_id BIGINT ,
    date_buy   TIMESTAMP WITHOUT TIME ZONE,
    quantity   INT    NOT NULL,
    amount     FLOAT  NOT NULL,
    receive_amount_seller FLOAT  NOT NULL,
    receive_amount_admin FLOAT  NOT NULL,
    CONSTRAINT pk_statistic PRIMARY KEY (id),
    CONSTRAINT fk_statistic_stat__buyer FOREIGN KEY (buyer_id) REFERENCES stat_buyer (id),
    CONSTRAINT fk_statistic_stat_product FOREIGN KEY (product_id) REFERENCES stat_product (id)
);