drop table if exists stat_buyer, stat_seller, stat_product, statistic_product, statistic_demo cascade;

CREATE TABLE IF NOT EXISTS stat_buyer
(
    id                BIGINT NOT NULL,
    name              VARCHAR(20) NOT NULL,
    CONSTRAINT pk_stat_buyer PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stat_seller
(
    id                BIGINT NOT NULL,
    name              VARCHAR(20)                 NOT NULL,
    CONSTRAINT pk_stat_seller PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS stat_product
(
    id                 BIGINT NOT NULL,
    name               VARCHAR(255)            NOT NULL,
    seller_id          BIGINT                  NOT NULL,
    CONSTRAINT pk_stat_product PRIMARY KEY (id),
    CONSTRAINT fk_stat_seller FOREIGN KEY (seller_id) REFERENCES stat_seller (id)
);

CREATE TABLE IF NOT EXISTS statistic_product
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    buyer_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    date_buy   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    quantity   INT    NOT NULL,
    profit     FLOAT  NOT NULL,
    profit_seller FLOAT  NOT NULL,
    profit_admin FLOAT  NOT NULL,
    CONSTRAINT pk_statistic_product PRIMARY KEY (id),
    CONSTRAINT fk_statistic_product_stat_buyer FOREIGN KEY (buyer_id) REFERENCES stat_buyer (id),
    CONSTRAINT fk_statistic_product_stat_product FOREIGN KEY (product_id) REFERENCES stat_product (id)
);

CREATE TABLE IF NOT EXISTS statistic_demo
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    buyer_id   BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity   INT    NOT NULL,
    CONSTRAINT pk_statistic_demo PRIMARY KEY (id),
    CONSTRAINT fk_statistic_demo_stat_buyer FOREIGN KEY (buyer_id) REFERENCES stat_buyer (id),
    CONSTRAINT fk_statistic_demo_stat_product FOREIGN KEY (product_id) REFERENCES stat_product (id)
);