DROP TABLE IF EXISTS buyers,sellers,admins,categories,licenses,vendors,countries,images,baskets,orders,statistics,products, requisites CASCADE;

CREATE TABLE IF NOT EXISTS buyers
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email             VARCHAR(254)                            NOT NULL,
    name              VARCHAR(254)                            NOT NULL,
    number            VARCHAR(254)                            NOT NULL,
    registration_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_buyer PRIMARY KEY (id),
    CONSTRAINT uq_buyer_email UNIQUE (email),
    CONSTRAINT uq_buyer_number UNIQUE (number)
);

CREATE TABLE IF NOT EXISTS requisites
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account VARCHAR(254)                            NOT NULL,
    CONSTRAINT pk_requisites PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS sellers
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email             VARCHAR(254)                            NOT NULL,
    first_name        VARCHAR(254)                            NOT NULL,
    last_name         VARCHAR(254)                            NOT NULL,
    number            VARCHAR(254)                            NOT NULL,
    registration_time TIMESTAMP WITHOUT TIME ZONE,
    requisites_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_seller PRIMARY KEY (id),
    CONSTRAINT uq_seller_email UNIQUE (email),
    CONSTRAINT uq_seller_number UNIQUE (number),
    CONSTRAINT fk_requisites FOREIGN KEY (requisites_id) REFERENCES requisites (id)
);

CREATE TABLE IF NOT EXISTS admins
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(254)                            NOT NULL,
    name  VARCHAR(254)                            NOT NULL,
    CONSTRAINT pk_admin PRIMARY KEY (id),
    CONSTRAINT uq_admin_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS images
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(254)                            NOT NULL,
    type VARCHAR(254)                            NOT NULL,
    size FLOAT                                   NOT NULL,
    data BYTEA                                   NOT NULL,
    CONSTRAINT pk_images PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(254)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS licenses
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(254)                            NOT NULL,
    price FLOAT                                   NOT NULL,
    CONSTRAINT pk_licenses PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS countries
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(254)                            NOT NULL,
    CONSTRAINT pk_countries PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS vendors
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(254)                            NOT NULL,
    description VARCHAR(1024)                           NOT NULL,
    image_id    BIGINT                                  NOT NULL,
    country_id  BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT fk_image FOREIGN KEY (image_id) REFERENCES images (id),
    CONSTRAINT fk_country FOREIGN KEY (country_id) REFERENCES countries (id)
);

CREATE TABLE IF NOT EXISTS products
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255)                            NOT NULL,
    description     VARCHAR(1024)                           NOT NULL,
    version         FLOAT                                   NOT NULL,
    production_time TIMESTAMP WITHOUT TIME ZONE,
    image_id        BIGINT                                  NOT NULL,
    category_id     BIGINT                                  NOT NULL,
    license_id      BIGINT                                  NOT NULL,
    vendor_id       BIGINT                                  NOT NULL,
    seller_id       BIGINT                                  NOT NULL,
    CONSTRAINT pk_products PRIMARY KEY (id),
    CONSTRAINT fk_image FOREIGN KEY (image_id) REFERENCES images (id),
    CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES categories (id),
    CONSTRAINT fk_license FOREIGN KEY (license_id) REFERENCES licenses (id),
    CONSTRAINT fk_vendor FOREIGN KEY (vendor_id) REFERENCES vendors (id),
    CONSTRAINT fk_seller FOREIGN KEY (seller_id) REFERENCES sellers (id)
);

CREATE TABLE IF NOT EXISTS baskets
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    buyer_id   BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    quantity   INT                                     NOT NULL,
    price      FLOAT                                   NOT NULL,
    CONSTRAINT pk_basket PRIMARY KEY (id),
    CONSTRAINT fk_buyer FOREIGN KEY (buyer_id) REFERENCES buyers (id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE IF NOT EXISTS orders
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    production_time TIMESTAMP WITHOUT TIME ZONE,
    amount          FLOAT,
    buyer_id        BIGINT                                  NOT NULL,
    product_id      BIGINT                                  NOT NULL,
    quantity        INT                                     NOT NULL,
    CONSTRAINT pk_order PRIMARY KEY (id),
    CONSTRAINT fk_buyer FOREIGN KEY (buyer_id) REFERENCES buyers (id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products (id)
);

CREATE TABLE IF NOT EXISTS statistics
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    buyer_id   BIGINT                                  NOT NULL,
    product_id BIGINT                                  NOT NULL,
    date_buy   TIMESTAMP WITHOUT TIME ZONE,
    quantity   INT                                     NOT NULL,
    amount     FLOAT                                   NOT NULL,
    CONSTRAINT pk_stats PRIMARY KEY (id),
    CONSTRAINT fk_buyer FOREIGN KEY (buyer_id) REFERENCES buyers (id),
    CONSTRAINT fk_product FOREIGN KEY (product_id) REFERENCES products (id)
);
